#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

#define LV_FONT_FMT_TXT_LARGE 1

#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_18 0
#define LV_FONT_MONTSERRAT_22 1
#define LV_FONT_MONTSERRAT_26 1
#define LV_FONT_MONTSERRAT_30 1
#define LV_FONT_MONTSERRAT_34 1
#define LV_FONT_MONTSERRAT_38 1
#define LV_FONT_MONTSERRAT_42 0
#define LV_FONT_MONTSERRAT_46 0
#define LV_FONT_MONTSERRAT_48 1

#define LV_FONT_SOURCE_HAN_SANS_SC_16_CJK 1

#define LV_FONT_DEFAULT &lv_font_montserrat_22

#endif